# Generated by Django 4.2.7 on 2023-11-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_user_managers_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
